# File: .github/workflows/repo-sync.yml
name: merge-from-config
on:
  schedule:
    - cron: '1 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ zero205 ]
  repository_dispatch:
    types: zero205
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: sync zero205
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zero205/JD_tencent_scf.git"
          source_branch: "config"
          destination_branch: "config"
          github_token: ${{ secrets.PAT }}
